sudo: required
services:
  - docker

before_install:
  - docker build -t camposss/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run camposss/react-test npm test -- --coverage

after_success:
  - docker build -t camposss/multi-client ./client
  - docker build -t camposss/multi-nginx ./nginx
  - docker build -t camposss/multi-server ./server
  - docker build -t camposss/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push camposss/multi-client
  - docker push camposss/multi-nginx
  - docker push camposss/multi-server
  - docker push camposss/multi-worker

deploy: 
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-499130248800
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY